# Generated by Django 3.1.3 on 2020-11-28 19:03

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20201123_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebelier',
            name='image',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=API.models.upload_location),
        ),
    ]
